blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def show
		@article = Article.find(
		params[:id]
		)
	end 

	def index 
		@articles = Article.all
	end	

	def new 
		@article = Article.new 
	end 

	def edit
		@article = Article.find(
			params[:id]
			)
	end 

	def create
		@article = Article.new(params.require(:article).permit(:title, :description))
		if @article.save
			flash[:notice] = 'Sucessfully saved'
			redirect_to article_path(@article)
		else 
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(params.require(:article).permit(:title, :description))
			flash[:notice] = 'Sucessfully updated'
			redirect_to article_path(@article)
		else 
			render 'new'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end 
end
	

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    
    end

    def about
    
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/pages_helper.rb
module PagesHelper
end

blog/app/views/articles/edit.html.erb
<h1>Update article</h1>

<% if @article.errors.any? %>
<h2>The following error occured</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
       <li><%= msg%></li>
    <% end %>
    </ul>
<% end %>

 
<%= form_with(model: @article, local: true) do |f|%>

<p>
<%=f.label :title%><br>
<%=f.text_field :title %>
</p>

<p>
<%=f.label :description%><br>
<%=f.text_area :description %>
</p>

<p>
<%=f.submit%>
</p>
<% end %>

blog/app/views/articles/index.html.erb
<h1>This is the article home page</h1>
<table>
    <thead> 
        <tr>
            <th> Title </th>
            <th> Description </th>
            <th colspan=3> Actions </th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
          <tr>
            <th> <%=article.title %> </th>  
            <th> <%=article.description %> </th>
            <th> <%= link_to 'Show', article_path(article.id)%></th>
            <th> <%= link_to 'Delete', article_path(article.id), method: :delete%></th>
            <th> <%= link_to 'Edit', edit_article_path(article.id) %></th>
          </tr>
        <% end %>
    </tbody>

</table>

<p>
<%= link_to 'Create new Article', new_article_path %>
</p>

blog/app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %>
<h2>The following error occured</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
       <li><%= msg%></li>
    <% end %>
    </ul>
<% end %>

 
<%= form_with scope: :article, url: articles_path, local: true do |f|%>

<p>
<%=f.label :title%><br>
<%=f.text_field :title %>
</p>

<p>
<%=f.label :description%><br>
<%=f.text_area :description %>
</p>

<p>
<%=f.submit%>
</p>
<% end %>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Delete', article_path(@article.id), method: :delete, data: {confirm: 'Are you sure'}%>
<%= link_to 'Edit', edit_article_path(@article.id) %>
<%= link_to 'Articles Path', articles_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjcetTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg%>
    <% end %>
      <%= yield %>
  </body>
</html>

blog/app/views/pages/about.html.erb
<h1> This is the about page</h1>
<%= link_to 'Article Listing', articles_path%>
<%= link_to 'Home', root_path%>

blog/app/views/pages/home.html.erb
<h1>
 This is the home page
</h1>

<%= link_to 'Article Listing', articles_path%>
<%= link_to 'About', about_path%>